#!/bin/sh
# exec is used to 'morph' the shell interpreter process into jackd process, saving some system resources.
exec /usr/bin/jackd -t 2000 -R -P 95 -d alsa -d hw:0,0 -r 48000 -p 512 -n 2 -X seq -s -S
